services:

  db:
    image: postgres:15-alpine
    container_name: db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    networks:
      - hybrid-micro-orm-net

networks:
  # docker network create hybrid-micro-orm-net || true
  hybrid-micro-orm-net:
    external: true